# Generated by Django 2.2.5 on 2019-09-16 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='variation',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='variation',
            name='item',
        ),
        migrations.RemoveField(
            model_name='order',
            name='ref_code',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='item_variations',
        ),
        migrations.DeleteModel(
            name='ItemVariation',
        ),
        migrations.DeleteModel(
            name='Variation',
        ),
    ]
